### ISSUE TITLE
I want to create multiple virtual hosts for nginx. Please help me.

### ISSUE THREAD

**Issue by furqank786** [nanoninja/docker-nginx-php-mysql#12]
@nanoninja @ZengLeiPro @ghostal @makros @letvinz

I want to create multiple virtual hosts for the single application available in the **web** directory.
I want to create new conf file for the virtual host and want to move same as the default.conf.
Tried with the same commands and steps in the yml file, also created new host variable in .env but did not work.
Please guide me to achieve multiple virtual hosts with multiple config files. 

Thanks in advance.

**Comment by furqank786** [comment]
@nanoninja @ZengLeiPro @ghostal @makros 

Please help me if anyone have idea about how to create multiple environment using virtual host for a single source code e.g. multi-tenancy application.
Thanks

**Comment by nanoninja** [comment]
@furqank786,

Hello,

This is not possible with this default configuration. Basically, the goal is to launch an instance for each project. This goal has not been fully met, but it will be. It is possible to integrate what you ask for, but you have to develop more to achieve this result.

I already managed to do it but it would be premature to add it knowing that it could break the existing.

This is an extract that works on code that I tested:

### .env
```sh
NGINX_HOST=domainA.com domainB.com domainC.com
```

### docker-compose.yaml
```yaml
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx:/etc/nginx/conf.d"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./scripts:/scripts"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /scripts/nginx.sh
        restart: always
        depends_on:
            - php
            - mysqldb
```

### nginx.sh
```sh
chmod +x /scripts/nginx.sh
```

```sh
for SERVER_NAME in $NGINX_HOST; do
  sed -e "s/\${NGINX_HOST}/$HOST/" /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/$SERVER_NAME.conf
  mkdir -p /var/www/html/$SERVER_NAME/public
done

nginx -g 'daemon off;'
```

For everything to work you have to manage all the commands that go together like certificate generation, composer management, etc...
