### ISSUE TITLE
phpMyAdmin -- Login Screen

### ISSUE THREAD

**Issue by zanematthew** [nanoninja/docker-nginx-php-mysql#25]
On the phpMyAdmin login screen how is the "Server:" setting derived? Currently I _can_ connect to the DB via PDO, but I cannot login via the pma screen.

I've recently adjusted the `NGINX_HOST`, and configured the phpMyAdmin and MySQL containers as follows;

```
myadmin:
  image: phpmyadmin/phpmyadmin
  container_name: ${APP_NAME}_phpmyadmin
  ports:
    - "8080:80"
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=${APP_NAME}_${MYSQL_HOST}
  restart: always
  depends_on:
    - mysqldb
mysqldb:
  image: mysql
  container_name: ${APP_NAME}_${MYSQL_HOST}
  restart: always
  env_file:
    - ".env"
  environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  ports:
    - "8989:3306"
  volumes:
    - "./database/data/db/mysql:/var/lib/mysql"
  networks:
    - esnet_new
```

I'm presuming my issue is something with the `container_name` I've set.

<img width="853" alt="screen shot 2018-04-04 at 8 59 58 am" src="https://user-images.githubusercontent.com/654712/38308939-970787e0-37e6-11e8-9f34-6ccd778d96cc.png">
